name: Deploy to Environments

on:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/your-project/nextjs-app:${{ github.ref_name }} .
          docker push gcr.io/your-project/nextjs-app:${{ github.ref_name }}

      - name: SSH into VM and deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull gcr.io/your-project/nextjs-app:${{ github.ref_name }}
            docker stop nextjs-${{ github.ref_name }} || true
            docker rm nextjs-${{ github.ref_name }} || true
            docker run -d --name nextjs-${{ github.ref_name }} -p 3000:3000 gcr.io/your-project/nextjs-app:${{ github.ref_name }}
